{{- if .Values.server.ingressRelay.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netbird.server.fullname" . }}-relay
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.server.labels" . | nindent 4 }}
  {{- $annotations := deepCopy (default (dict) .Values.server.ingressRelay.annotations) }}
  {{- if .Values.server.relaySidecar.tls.enabled }}
    {{- $_ := set $annotations "nginx.ingress.kubernetes.io/ssl-passthrough" "true" }}
    {{- $_ := set $annotations "nginx.ingress.kubernetes.io/backend-protocol" "HTTPS" }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.ingressRelay.className }}
  ingressClassName: {{ .Values.server.ingressRelay.className }}
  {{- end }}
  {{- if .Values.server.ingressRelay.tls }}
  tls:
    {{- range .Values.server.ingressRelay.tls }}
    - secretName: {{ .secretName }}
      hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.server.ingressRelay.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
    {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "netbird.server.fullname" $ }}
                port:
                  name: {{ include "netbird.relays.relayBackendPortName" $ }}
    {{- end }}
  {{- end }}
{{- end }}

