apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
{{- if and .Values.server.config.relays.enabled .Values.server.config.relays.embedded.enabled }}
    - name: relay
      port: {{ .Values.server.relaySidecar.listenPort }}
      targetPort: relay
      protocol: TCP
{{- end }}
  selector:
    {{- include "netbird.server.selectorLabels" . | nindent 4 }}

