{{- include "netbird.validate.exposedAddress" . -}}
{{- include "netbird.validate.routeExclusion" . -}}
{{- include "netbird.validate.relayTls" . -}}
{{- include "netbird.validate.relays" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.server.labels" . | nindent 4 }}
data:
  config.yaml.tpl: |
    {{- include "netbird.server.configTemplate" . | nindent 4 }}
{{- if eq (include "netbird.database.isExternal" .) "true" }}
  seed.yaml: |
    {{- include "netbird.database.seedSpec" . | nindent 4 }}
{{- end }}
